<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$stripeConfig = $this->helper("\Magenest\Stripe\Helper\Config");
$isSave = $stripeConfig->isSave();
$getCardUrl = $block->getUrl("stripe/customer/getCard");
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= /* @noEscape */ $code ?>"
          style="display:none"
          data-bind="scope: 'stripe_payment_form'">

    <input type="hidden" name="payment[customer_id]" id="magento-customer-id-input">
    <div class="field-type admin__field _required" id="stripe-save-card-div" data-bind="afterRender: getSaveCardData, visible: showSelectCard">
        <label class="admin__field-label" for="stripe-save-card">
            <span><?= $block->escapeHtml(__('Choose Card')) ?></span>
        </label>
        <div class="admin__field-control">
            <select name="payment[source_id]" class="admin__control-select"
                    data-bind="attr: {id: 'stripe-save-card'},
                           options: customerCard,
                           optionsText: function(item) {
                               return 'xxxxxxxxxxxx'+item.last4 + ' (' + item.brand + ')'
                           },
                           optionsValue: function(item) {return item.card_id},
                           optionsCaption: 'Select card',
                           value: cardId
                           ">
            </select>
        </div>
    </div>

    <div class="field-type admin__field _required" data-bind="visible: useCCField">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_type">
            <span><?= $block->escapeHtml(__('Credit Card Type')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_cc_type" name="payment[cc_type]"
                    class="validate-cc-type-select admin__control-select"
                    data-bind="css: {'required-entry': useCCField}"
            >
                <option value=""></option>
                <?php foreach ($block->getCcAvailableTypes() as $typeCode => $typeName): ?>
                    <option value="<?= $block->escapeHtml($typeCode) ?>" <?php if ($typeCode == $ccType): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($typeName) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>
    <div class="field-number admin__field _required" data-bind="visible: useCCField">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_number">
            <span><?= $block->escapeHtml(__('Credit Card Number')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="<?= /* @noEscape */ $code ?>_cc_number" name="payment[cc_number]"
                   title="<?= $block->escapeHtml(__('Credit Card Number')) ?>" class="admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('cc_number') ?>"
                   data-bind="css: {'validate-cc-number': useCCField}"
            />
        </div>
    </div>
    <div class="field-date admin__field _required" data-bind="visible: useCCField">
        <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_expiration">
            <span><?= $block->escapeHtml(__('Expiration Date')) ?></span>
        </label>
        <div class="admin__field-control">
            <select id="<?= /* @noEscape */ $code ?>_expiration" name="payment[cc_exp_month]"
                    class="admin__control-select admin__control-select-month validate-cc-exp"
                    data-bind="css: {'required-entry': useCCField}"
            >
                <?php foreach ($block->getCcMonths() as $k => $v): ?>
                    <option value="<?= $block->escapeHtml($k) ?>"
                            <?php if ($k == $ccExpMonth): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <select id="<?= /* @noEscape */ $code ?>_expiration_yr" name="payment[cc_exp_year]"
                    class="admin__control-select admin__control-select-year"
                    data-bind="css: {'required-entry': useCCField}"
            >
                <?php foreach ($block->getCcYears() as $k => $v): ?>
                    <option value="<?= /* @noEscape */ $k ? $block->escapeHtml($k) : '' ?>"
                            <?php if ($k == $ccExpYear): ?>selected="selected"<?php endif ?>>
                        <?= $block->escapeHtml($v) ?>
                    </option>
                <?php endforeach ?>
            </select>
        </div>
    </div>

    <?php if ($block->hasVerification()): ?>
        <div class="field-number required admin__field _required" data-bind="visible: useCCField">
            <label class="admin__field-label" for="<?= /* @noEscape */ $code ?>_cc_cid">
                <span><?= $block->escapeHtml(__('Card Verification Number')) ?></span>
            </label>
            <div class="admin__field-control">
                <input type="text" title="<?= $block->escapeHtml(__('Card Verification Number')) ?>"
                       class="validate-cc-cvn admin__control-cvn admin__control-text"
                       id="<?= /* @noEscape */ $code ?>_cc_cid"
                       name="payment[cc_cid]" value="<?= /* @noEscape */ $block->getInfoData('cc_cid') ?>"
                       data-bind="css: {'required-entry': useCCField}"
                />
            </div>
        </div>
    <?php endif; ?>
</fieldset>

<script>
    require([
        'jquery',
        'prototype',
        'Magento_Sales/order/create/scripts',
        "Magento_Sales/order/create/form"

    ], function($){
        order.addExcludedPaymentMethod('<?php /* @noEscape */ echo $code; ?>');
        window.stripe_customer_id = order.customerId;
        $('#get_save_card').click(function () {
            $.ajax({
                method: "POST",
                url: '<?=$block->getUrl('stripe/customer/getCard')?>',
                data: {'customer_id': customerId},
                success: function (response) {
                    if(response.success){
                        $('#stripe-save-card-div').show();
                        $('#stripe-save-card').html(response.html);
                        $("#magento-customer-id-input").val(customerId);
                    }
                },
                dataType: 'json'
            })
        });

    });
</script>

<script type="text/x-magento-init">
    {
         "#payment_form_<?= /* @noEscape */ $code ?>": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "stripe_payment_form": {
                            "component": "Magenest_Stripe/js/payment_info",
                            "getCardUrl": "<?=$getCardUrl?>"
                        }
                    }

                }
         }
    }

</script>
