<div class="works-section">
  <div class="home-container">
  <div class="section-heading">
    <h2> <strong>How it all </strong> works</h2>
  </div>
  <div class="work-content">
    <div class="work-content-block">
      <!-- <img src="" height="70" alt="docs-org"> -->
        <img src="<?php echo $block->getViewFileUrl('images/docs.png'); ?>" height="70" alt="docs-org" />
      <h4>Subscribe</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent finibus euismod rutrum.</p>
      <a href="#">Read more</a>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/calender-icon.png'); ?>" height="70" alt="calender-icon" />
      <h4>Tracking</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent finibus euismod rutrum.</p>
      <a href="#">Read more</a>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/Transport-Truck-icon.png'); ?>" height="70" alt="Transport-Truck-icon" />
      <h4>delivery</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent finibus euismod rutrum.</p>
      <a href="#">Read more</a>
    </div>
  </div>
</div>
</div>
<div class="curve"></div>
