<div class="works-section">
  <div class="home-container">
  <div class="section-heading">
    <h2> <strong>How it </strong> works</h2>
  </div>
  <div class="work-content">
    <div class="work-content-block">
      <!-- <img src="" height="70" alt="docs-org"> -->
        <img src="<?php echo $block->getViewFileUrl('images/c1.png'); ?>" height="70" alt="kit-icon" />
      <h4>Choose your kit</h4>
      <p>You can choose 1,2 or all 3 products of the available kits. Choosing more than 2 products gets you free samples of our member-only, premium health care products.</p>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/c2.png'); ?>" height="70" alt="second-box-icon" />
      <h4>From your second box onward….</h4>
      <p>We’ll send you replacements of the nootropics you picked for your first box. You can add to your box at any time.</p>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/c3.png'); ?>" height="70" alt="commitments-icon" />
      <h4>No long term commitments</h4>
      <p>You can cancel your subscription anytime with a few clicks. You do get a 20% drop in your monthly subscription price if you stay for more than nine months, but it’s a perk and not an obligation.</p>
    </div>
  </div>
  <div class="section-button">
    <a href="/how-it-works"><button type="button">READ MORE</button></a>
  </div>
</div>
</div>
<div class="curve">
  <img src="<?php echo $block->getViewFileUrl('images/curve.jpg'); ?>" alt="Shadow" />
</div>
