<div class="works-section">
  <div class="home-container">
  <div class="section-heading">
    <h2> <strong>How it </strong> works</h2>
  </div>
  <div class="work-content">
    <div class="work-content-block">
      <!-- <img src="" height="70" alt="docs-org"> -->
        <img src="<?php echo $block->getViewFileUrl('images/c1.png'); ?>" height="70" alt="kit-icon" />
      <h4>Choose your kit</h4>
      <p>You can choose 1, 2 or all 3 products of the available kits. Choosing 2 or more gets you a discount.</p>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/c2.png'); ?>" height="70" alt="second-box-icon" />
      <h4>Get Replacement</h4>
      <p>
We’ll send you replacements of the products you picked for your first box. You can add to your box at any time.</p>
    </div>
    <div class="work-content-block">
      <img src="<?php echo $block->getViewFileUrl('images/c3.png'); ?>" height="70" alt="commitments-icon" />
      <h4>No long-term commitments</h4>
      <p>Cancel your subscription anytime with a few clicks. Or, stay for more than six months and get a 15% monthly discount.</p>
    </div>
  </div>
  <div class="section-button">
    <a href="/how-it-works"><button type="button">READ MORE</button></a>
  </div>
</div>
</div>
<div class="curve">
  <img src="<?php echo $block->getViewFileUrl('images/curve.jpg'); ?>" alt="Shadow" />
</div>
