<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>
<div class="sections nav-sections">
  <div class="section-items nav-sections-items" data-mage-init='{"tabs":{"openedState":"active"}}'>
    <div class="section-item-title nav-sections-item-title" data-role="collapsible">
      <a class="nav-sections-item-switch" data-toggle="switch" href="#store.menu">Menu</a>
    </div>
    <div class="section-item-content nav-sections-item-content" id="store.menu" data-role="content">
      <nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-1 first last level-top ui-menu-item" role="presentation">
          <a href="<?php echo $block->getBaseUrl(); ?>get-started" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>get started</span>
          </a>
        </li>
        <li class="level0 nav-2 first last level-top ui-menu-item" role="presentation">
          <a href="<?php echo $block->getBaseUrl(); ?>how-it-works" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>how it works</span>
          </a>
        </li>
        <li class="level0 nav-3 first last level-top ui-menu-item">
          <a href="<?php echo $block->getBaseUrl(); ?>" class="level-top ui-corner-all  menu-logo" id="ui-id-3" tabindex="-1" role="menuitem">
          <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" />
        </a>
        </li>
        <li class="level0 nav-4 first level-top ui-menu-item" role="presentation">
          <a href="<?php echo $baseUrl .'products';?>" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>products</span>
          </a>
        </li>
        <?php echo $this->getChildHtml('customer');?>
        <li class="level0 first last level-top ui-menu-item desktop-none" role="presentation">
          <a href="<?php echo $baseUrl . 'customer/account/logout/'; ?>" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>Sign Out</span>
          </a>
        </li>
        <li class="level0 nav-6 first level-top ui-menu-item" role="presentation">
        </li>
  </ul>
</nav>
    </div>
  </div>
</div>
<script>
require([
      'jquery',
  ], function($) {
    var lastScrollTop = 0;
    $(window).scroll(function(event){
       var st = $(this).scrollTop();
       if (st > lastScrollTop){
           // downscroll code
               $(".sections.nav-sections,.minicart-wrapper").addClass("scrollDown").removeClass("scrollUp");
       }
       else {
          // upscroll code
               $(".sections.nav-sections,.minicart-wrapper").addClass("scrollUp").removeClass("scrollDown");
       }
       lastScrollTop = st;
    });
  });
</script>
