<div class="footer-links">
	<?php
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer1')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer2')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer3')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer4')
	          ->toHtml();
	?>
</div>
