<!-- Homepage Flagships Static Block -->

<!-- fdvdfvfdv -->
<!-- fdvfdvdfvdddddddddddddddddddddddddddddddddddddddddddddddddddddf -->
<!-- fddvaaaaaaaaaaaaaaaassssssssssssssssssssssssssssssssss -->

<span class="youtube-link" youtubeid="yPu6qV5byu4">Open Video 1 - (dark theme - autoplay enabled)</span><br />

<div class="flagships-static padding-70">
  <div class="home-container">
    <div class="section-heading">
      <h2><strong>Our</strong>Flagships</h2>
    </div>
    <div class="row">
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Metanine.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Metanine</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
        <div class="overlay">
          <div class="flag-content">
            <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
            <div class="flag-button">
            <a class="button-style border-white" href="#">View all</a>
          </div>
          </div>
        </div>
      </div>
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Enkodin.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Enkodin</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
        <div class="overlay">
          <div class="flag-content">
            <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
            <div class="flag-button">
            <a class="button-style border-white" href="#">View all</a>
          </div>
          </div>
        </div>
      </div>
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Xance.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Xance</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
        <div class="overlay">
          <div class="flag-content">
            <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
            <div class="flag-button">
            <a class="button-style border-white" href="#">View all</a>
          </div>
          </div>
        </div>
      </div>
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Jubilin.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Jubilin</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
        <div class="overlay">
          <div class="flag-content">
            <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
            <div class="flag-button">
            <a class="button-style border-white" href="#">View all</a>
          </div>
          </div>
        </div>
      </div>
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Seraxil.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Seraxil</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
</div>
<div class="overlay">
  <div class="flag-content video-link4 demo-link">
    <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
    <div class="flag-button">
    <a class="button-style border-white" href="#">View all</a>
  </div>
  </div>
</div>
      </div>
      <div class="section-product">
        <div class="product-image"><img src="{{media url="wysiwyg/Myeliv.png"}}" alt="" /></div>
        <div class="product-content">
          <h4>Myeliv</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
        </div>
        <div class="overlay">
          <div class="flag-content">
            <img src="<?php echo $block->getViewFileUrl('images/video.png'); ?>" height="50" alt="docs-org" />
            <div class="flag-button">
            <a class="button-style border-white" href="#">View all</a>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="curve-white"></div>
<script type="text/x-magento-init">
    // {
    //   videoLightning({
    //     elements: [
    //       {
    //         ".video-link": {
    //           autoplay: 1,
    //           easeOut: 1000,
    //           bdColor: "#ddd",
    //           bdOpacity: 0.6,
    //           glow: 20,
    //           glowColor: "#000"
    //         }
    //       },
    //       {
    //         "#bare-iframe-link": {
    //           id: 'f-images/JqueryVideoLightningIconPurple144.png',
    //           frameColor: '#555',
    //           frameBorder: '3px solid #3A0372',
    //           bdOpacity: 0.9,
    //           glow: 0,
    //           xBgColor: '#3A0372',
    //           xColor: '#f5f5f5',
    //           xBorder: '3px solid #555'
    //         }
    //       }
    //     ]
    //   });
    //   // $(function () {
    //   //     $(".video-link4").jqueryVideoLightning({
    //   //         id: 'y-26mMPKS83c4',
    //   //         autoplay: 1,
    //   //         startTime: 62,
    //   //         fadeIn: 0,
    //   //         bdColor: '#f5f5f5',
    //   //         bdOpacity: 1,
    //   //         glow: 20,
    //   //         glowColor: '#000',
    //   //         controls: 0,
    //   //         showinfo: 0,
    //   //         color: "white"
    //   //     });
    //   // });
    // }
</script>
<script>
  require([
        'jquery',
        'videopopup'
    ], function($) {

          alert("hi");
          $(".youtube-link").grtyoutube({
    				autoPlay:true,
    				theme: "dark"
    			});

    });

</script>
