<div class="footer-bottom">
    <!-- Footer Extra Link Block -->
  <div class="footer-bottom-link">
    <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-bottom-links')
                ->toHtml();
    ?>
  </div>
  <!-- Footer Payments Block -->
  <div class="footer-payments">
    <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-payments')
                ->toHtml();
    ?>
  </div>
  <!-- Footer Logo  -->
  <div class="footer-logo">
    <img src="<?php echo $block->getViewFileUrl('images/footer-logo.png'); ?>" />
  </div>
  <div class="clearfix"></div>
  <!-- Footer Disclaimer Block -->
  <div class="footer-cms-links">
    <?php
        echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-cms-links')
                ->toHtml();
    ?>
  </div>
  <div class="footer-disclaimer">
    <?php
        echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-disclaimer')
                ->toHtml();
    ?>
  </div>


  <!-- Footer Copyright Block -->
  <div class="footer-copyright">
    <?php
      echo $this->getLayout()
              ->createBlock("Magento\Theme\Block\Html\Footer")
              ->setTemplate("Magento_Theme::html/copyright.phtml")
              ->toHtml();
    ?>
  </div>
</div>
