<!-- Footer Links -->
<div class="footer-links">
	<?php
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer-links1')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer-links2')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer-links3')
	          ->toHtml();
		echo $this->getLayout()
	          ->createBlock('Magento\Cms\Block\Block')
	          ->setBlockId('footer-links4')
	          ->toHtml();
	?>
</div>
