<!-- blog section in the home page begins here  -->
<div class="blog-section margin">
  <div class="section-heading">
    <h2><strong>Neuro </strong> Blogs</h2>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
       Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
  </div>
  <div class="blog-container">
    <div class="blog-content">
      <div class="blog-content-block">
        <img src="<?php echo $block->getViewFileUrl('images/blog-image-1.png'); ?>" alt="Blog-Image" />
        <div class="blog-content-details">
          <h4>Lorem ipsum dolar sit</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          <a href="#">Read more</a>
          </div>
      </div>
      <div class="blog-content-block">
        <img src="<?php echo $block->getViewFileUrl('images/blog-image-2.png'); ?>" alt="Blog-Image" />
        <div class="blog-content-details">
          <h4>Lorem ipsum dolar sit</h4>
          <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.
            Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
            when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          <a href="#">Read more</a>
          </div>
      </div>
    </div>
    <div class="section-button">
      <button type="button">view all</button>
    </div>
  </div>
</div>
