<div class="home-product-slider">
  <div id="owl-product" class="padding-70" data-mage-init='{
  "OwlCarousel":{
      "center": true,
      "margin":10,
      "autoPlay": 3000,
      "pagination": false,
      "items": 3,
      "itemsDesktop" : [1199,3],
      "itemsDesktopSmall" : [979,1],
      "itemsTablet" : [768, 1]
  }
}
'>
  <div class="item">
    <img src="<?php echo $block->getViewFileUrl('images/medicine.png'); ?>" class="image" height="70" alt="docs-org" />
    <h2>FEEL ALIVE - ENERGY PACK</h2>
    <h5>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</h5>
    <a class="button" href="#">Subscribe | ₹ 999.99</a>
    <h3>Lorem ipsum dolar sit</h3>
    <div class="product-row">
      <div class="row">
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
      </div>
    </div>
  </div>
  <div class="item">
    <img src="<?php echo $block->getViewFileUrl('images/medicine.png'); ?>" class="image" height="70" alt="docs-org" />
    <h2>FEEL ALIVE - ENERGY PACK</h2>
    <h5>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</h5>
    <a class="button" href="#">Subscribe | ₹ 999.99</a>
    <h3>Lorem ipsum dolar sit</h3>
    <div class="product-row">
      <div class="row">
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
      </div>
    </div>
  </div>
  <div class="item">
    <img src="<?php echo $block->getViewFileUrl('images/medicine.png'); ?>" class="image" height="70" alt="docs-org" />
    <h2>FEEL ALIVE - ENERGY PACK</h2>
    <h5>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</h5>
    <a class="button" href="#">Subscribe | ₹ 999.99</a>
    <h3>Lorem ipsum dolar sit</h3>
    <div class="product-row">
      <div class="row">
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
      </div>
    </div>
  </div>
  <div class="item">
    <img src="<?php echo $block->getViewFileUrl('images/medicine.png'); ?>" class="image" height="70" alt="docs-org" />
    <h2>FEEL ALIVE - ENERGY PACK</h2>
    <h5>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</h5>
    <a class="button" href="#">Subscribe | ₹ 999.99</a>
    <h3>Lorem ipsum dolar sit</h3>
    <div class="product-row">
      <div class="row">
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
        <div class="sub-product">
          <img src="<?php echo $block->getViewFileUrl('images/product.png'); ?>" height="70" alt="docs-org" />
          <h4>Metanine </h4>
          <h4>30 Capsule pack</h4>
          <h6>Lorem ipsum dolar</h6>
          <p>₹ 999.99</p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script type="text/x-magento-init">
    {
        "#owl-product": {
            "OwlCarousel": {
                "center": true,
                "margin":10,
                "autoPlay": 3000,
                "pagination": false,
                "items": 3,
                "itemsDesktop": [1199, 3],
                "itemsDesktopSmall" : [979,1],
                "itemsTablet" : [768, 1]
            }
        }
    }
</script>
