<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-1 first last level-top ui-menu-item" role="presentation">
          <a href="<?php echo $block->getBaseUrl(); ?>get-started" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>get started</span>
          </a>
        </li>
        <li class="level0 nav-2 first last level-top ui-menu-item" role="presentation">
          <a href="<?php echo $block->getBaseUrl(); ?>how-it-works" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>how it works</span>
          </a>
        </li>
        <li class="level0 nav-2 first last level-top ui-menu-item" role="presentation">
          <a href="<?php echo $block->getBaseUrl(); ?>club-exclusive" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>club exclusive</span>
          </a>
        </li>
        <li class="level0 nav-3 first last level-top ui-menu-item">
          <a href="<?php echo $block->getBaseUrl(); ?>" class="level-top ui-corner-all  menu-logo" id="ui-id-3" tabindex="-1" role="menuitem">
          <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" />
        </a>
        </li>
        <li class="level0 nav-4 first level-top ui-menu-item" role="presentation">
          <a href="<?php echo $baseUrl .'products';?>" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>products</span>
          </a>
        </li>
        <?php if(!$customerSession->isLoggedIn()) { echo $customerSession->isLoggedIn(); ?>
           <li class="level0 nav-5 first last level-top ui-menu-item" role="presentation">
             <a href="<?php echo $baseUrl . 'customer/account/login/'; ?>" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
               <span>Sign In</span>
             </a>
           </li>
          <?php } else {?>
                <li class="level0 nav-5 first last level-top ui-menu-item desktop-none" role="presentation">
                  <a href="<?php echo $baseUrl . 'customer/account/logout/'; ?>" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
                    <span>Sign Out</span>
                  </a>
                </li>
                <li class="level0 nav-5 first last level-top ui-menu-item" role="presentation">
               <?php echo $this->getChildHtml('customer') ?>
             </li>
           <?php } ?>
        <li class="level0 nav-6 first level-top ui-menu-item" role="presentation">
        </li>
  </ul>
</nav>
