<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <li class="level0 nav-1 first level-top ui-menu-item" role="presentation">
          <a href="#" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>get started</span>
          </a>
        </li>
        <li class="level0 nav-2 first level-top ui-menu-item" role="presentation">
          <a href="#" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>how it works</span>
          </a>
        </li>
        <li class="level0 nav-3 first level-top ui-menu-item">
          <a href="#" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
              <img src="<?php echo $block->getViewFileUrl('images/logo.png'); ?>" />
          </a>
        </li>
        <li class="level0 nav-4 first level-top ui-menu-item" role="presentation">
          <a href="#" class="level-top ui-corner-all" id="ui-id-3" tabindex="-1" role="menuitem">
            <span>products</span>
          </a>
        </li>
        <?php echo $this->getChildHtml('customer') ?>
        <li class="level0 nav-6 first last level-top ui-menu-item" role="presentation">
            <?php echo $this->getChildHtml('minicart') ?>
        </li>
  </ul>
</nav>
