<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
?>
<div class="plp-bottom">
    <div class="inner-container">
        <div class="row plp-bottom-container">
            <img src='<?php echo  $block->getBaseUrl() . "pub/media/catalog/category/" . $category->getData('category_banner_image'); ?>'/>
            <a href="<?php echo $category->getData('category_banner_link') ?>">
                <div class="section-button plp-bottom-button">
                    <button>Shop Now</button>
                </div>
            </a>
        </div>
    </div>
</div>
