<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
?>
<div class="plp-bottom">
    <div class="inner-container">
        <div class="plp-bottom-container">
            <a href="<?php echo $category->getData('category_banner_link') ?>">
              <img src='<?php echo  $block->getBaseUrl() . "pub/media/catalog/category/" . $category->getData('category_banner_image'); ?>'/>
            </a>
        </div>
    </div>
</div>
