<?php $isEnable = $block->getConfig('faqtab/general/enable') ?>
<?php $showGroup = $block->getConfig('faqtab/general/showgroup') ?>
<?php //$showGroupTitle = $block->getConfig('faqtab/general/showgrouptitle') ?>
<?php $faqGroupCollection = $block->getFaqGroupCollection() ?>
<?php if ($faqGroupCollection->getSize()) : ?>
    <?php if ($isEnable) : ?>
      <div class="home-container">
    <div class="faq-collection margin">
    <div class="section-heading">
      <h2><strong>Frequently </strong>Asked Questions</h2>
    </div>
        <div class="faq-content">
            <?php foreach ($faqGroupCollection as $group) : ?>
                <div class="faq-accordion">
                <?php $faqLatest = $block->getFaqLatest(); ?>
                    <?php if (count($faqLatest) > 0) : ?>
                      <?php //var_dump($faqLatest);?>
                        <?php foreach ($faqLatest as $faq) : ?>
                            <h3><?php /* @noEscape */ echo $faq['title']; ?></h3>
                            <div>
                                <p><?php /* @noEscape */ echo $block->filterOutputHtml($faq['content']); ?></p>
                            </div>
                        <?php endforeach; ?>
                    <?php else : ?>
                        <div><?php /* @noEscape */ echo __('No FAQ available'); ?></div>
                    <?php endif; ?>
                </div>
            <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
        <div class="section-button">
        <a href="<?php echo $block->getBaseUrl(); ?>faq"><button type="button">VIEW ALL</button></a>
      </div>
    </div>
    </div>
    <?php endif; ?>
<?php else : ?>
    <div>
        <h1><?php /* @noEscape */ echo __('No FAQ Group available'); ?></h1>
    </div>
<?php endif; ?>
