<?php $product = $block->getProduct() ?>
<?php if (null !== $product->getCustomAttribute('product_youtube_video')): ?>
  <div class="pdp-video-banner-container">
    <div class="video-content">
      <div class="video-outer">
        <iframe src="<?php echo $product->getCustomAttribute('product_youtube_video')->getValue() ?>" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
    </div>
  </div>
<?php endif; ?>
