<?php $product = $block->getProduct() ?>
<?php if (null !== $product->getCustomAttribute('product_video')): ?>
  <div class="pdp-video-container">
    <h4>How It Works</h4>
    <div class="video-content">
      <div class="video-outer">
        <iframe src="<?php echo $product->getCustomAttribute('product_video')->getValue() ?>" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
      </div>
      <?php if (null !== $product->getCustomAttribute('product_video_description')): ?>
      <div class="video-description">
        <?php echo $product->getCustomAttribute('product_video_description')->getValue() ?>
      </div>
      <?php endif; ?>
    </div>
  </div>
  <div class="curve">
    <img src="<?php echo $block->getViewFileUrl('images/curve.jpg'); ?>" alt="Shadow" />
  </div>
<?php endif; ?>
