<?php if ($exist = $block->getProductSkuArray()): ?>
     <?php
     $type = 'widget-product-grid';

     $mode = 'grid';

     $image = 'new_products_content_widget_grid';

     $showWishlist = true;
     $showCompare = true;
     $showCart = true;
     $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
     $description = false;
     $flagships = $block->getProductSkuArray();
     $flagship_products = explode(',', $flagships);
     ?>
     <div class="block widget block-products-list <?php /* @noEscape */ echo $mode; ?>">
         <div class="block-content">
             <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
             <div class="products-<?php /* @noEscape */ echo $mode; ?> <?php /* @noEscape */ echo $mode; ?>">
                 <ol class="product-items <?php /* @noEscape */ echo $type; ?>">
                     <?php $iterator = 1; ?>
                     <?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
                     <?php foreach ($flagship_products as $flagships_sku): ?>
                       <?php $productId = $objectManager->get('Magento\Catalog\Model\ResourceModel\Product')->getIdBySku($flagships_sku); ?>
                       <?php $_item = $objectManager->get('Magento\Catalog\Model\Product')->load($productId);?>
                       <?php if ($iterator++ != 1): ?></li><?php endif ?>
                       <li class="product-item">
                           <div class="product-item-info">
                               <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                   <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                               </a>
                               <div class="product-item-details">
                                   <strong class="product-item-name">
                                       <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                          href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                          class="product-item-link">
                                           <?php echo $block->escapeHtml($_item->getName()) ?>
                                       </a>
                                   </strong>
                                   <?php
                                   echo $block->getProductPriceHtml($_item, $type);
                                   ?>

                                   <?php if ($templateType): ?>
                                       <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                   <?php endif; ?>

                                   <?php if ($showWishlist || $showCompare || $showCart): ?>
                                       <div class="product-item-actions">
                                           <?php if ($showCart): ?>
                                               <div class="actions-primary">
                                                   <?php if ($_item->isSaleable()): ?>
                                                       <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                           <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                                               <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
                                                           </button>
                                                       <?php else: ?>
                                                           <?php
                                                           $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                           $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                           ?>
                                                           <button class="action tocart primary" data-post='<?php /* @noEscape */ echo $postData; ?>' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                                               <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
                                                           </button>
                                                       <?php endif; ?>
                                                   <?php else: ?>
                                                       <?php if ($_item->getIsSalable()): ?>
                                                           <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                                       <?php else: ?>
                                                           <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                       <?php endif; ?>
                                                   <?php endif; ?>
                                               </div>
                                           <?php endif; ?>
                                       </div>
                                   <?php endif; ?>
                               </div>
                           </div>
                           <?php echo($iterator == count($flagship_products)+1) ? '</li>' : '' ?>
                         <?php endforeach ?>
                 </ol>
             </div>
             <?php echo $block->getPagerHtml() ?>
         </div>
     </div>
 <?php endif;?>
