<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<div class="company">
  <ul class="company-facts">
    <li><span>100%:</span> Safe and Secure Payments </li>
    <li><span>TrustPay:</span> 100% Payment Protection, Easy Returns Policy</li>
    <li><span>Free &amp; Easy</span> Returns</li>
  </ul>
</div>
<div class="continue-shopping">
  <button type="button" name="button">Continue Shopping</button>
</div>

<div>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <button type="button"
            data-role="proceed-to-checkout"
            title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
            class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <span><?= /* @escapeNotVerified */ __('Place Order') ?></span>
    </button>
<?php endif?>
</div>
