<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
  <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
  <?php
    $viewMode = 'list';
    $image = 'category_page_list';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    /**
    * Position for actions regarding image size changing in vde if needed
    */
    $pos = $block->getPositioned();
  ?>
  <div class="plp-container">
    <!-- <div class="section-heading plp-heading">
      <h2><strong>Our </strong>Flagships</h2>
    </div> -->
    <div class="plp-item-container">
      <?php $iterator = 1; ?>
      <?php foreach ($_productCollection as $_product): ?>
          <div class="plp-item">
            <div class="inner-container">
              <?php
                $productImage = $block->getImage($_product, $image);
                if ($pos != null) {
                  $position = ' style="left:' . $productImage->getWidth() . 'px;'
                    . 'top:' . $productImage->getHeight() . 'px;"';
                }
              ?>
              <?php // Product Image ?>
              <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                <div class="item-image">
                  <?= $productImage->toHtml() ?>
                </div>
              </a>
              <div class="item-content">
                <h6>
                  <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $block->stripTags($_product->getName(), null, true) ?>">
                    <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                  </a>
                </h6>
                <div class="medicine-type">
                  <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                </div>
                <div class="description">
                  <?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?>
                </div>
                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                <?= $block->getProductDetailsHtml($_product) ?>
                <div class="product-item-inner">
                  <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                      <?php if ($_product->isSaleable()): ?>
                        <div class="section-button plp-item-button">
                          <button class="button button-style-1" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getProductUrl($_product)) ?>"}}' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                            <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span> | <?= /* @escapeNotVerified */ $priceHelper->currency($_product->getFinalPrice(), true, false) ?>
                          </button>
                        </div>
                      <?php else: ?>
                        <?php if ($_product->isAvailable()): ?>
                          <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                        <?php else: ?>
                          <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                        <?php endif; ?>
                      <?php endif; ?>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php $iterator++; ?>
      <?php endforeach; ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
      <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
  </div>
<?php endif; ?>
<div class="plp-bottom">
  <div class="inner-container">
    <div class="row plp-bottom-container">
      <?php
        echo $this->getLayout()
                   ->createBlock('Magento\Cms\Block\Block')
                   ->setBlockId('flagships-listing-page-banner')
                   ->toHtml();
       ?>
    </div>
  </div>
</div>
