<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $iterator = $block->getProductCollection()->getSize();
    ?>
    <?php foreach ($items as $_item): ?>
        <div class="product-item">
            <div class="product-title">
                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                      href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>">
                      <?php echo $block->escapeHtml($_item->getName()) ?>
                </a>
            </div>
            <h5>
                <?php echo $this->helper('Quinoid\CatalogWidget\Helper\Product\Description')->getProductDescription($_item); ?>
            </h5>
            <?php if ($showCart): ?>
                <div class="actions-primary">
                    <?php if ($_item->isSaleable()): ?>
                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                            <button class="button button-style-1" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span> | <?= /* @escapeNotVerified */ $priceHelper->currency($_item->getFinalPrice(), true, false) ?>
                            </button>
                        <?php else: ?>
                            <?php
                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                            ?>
                            <button class="button" data-post='<?php /* @noEscape */ echo $postData; ?>' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span> | <?= /* @escapeNotVerified */ $priceHelper->currency($_item->getFinalPrice(), true, false) ?>
                            </button>
                        <?php endif; ?>
                        <div class="product-item-price">
                            <?php echo $block->getProductPriceHtml($_item, $type) ?>
                        </div>
                    <?php else: ?>
                        <?php if ($_item->getIsSalable()): ?>
                            <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                        <?php else: ?>
                            <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
            <h3>BUNDLED ITEMS</h3>
            <div class="product-row">
                <?php
                $typeInstance = $_item->getTypeInstance();
                $requiredChildrenIds = $typeInstance->getChildrenIds($_item->getId(), true);
                foreach ($requiredChildrenIds as $key => $childIdArr) {}
                if ($childIdArr != null) {
                    foreach ($childIdArr as $childId) {
                        $childItem = $objectManager->get('Magento\Catalog\Model\Product')->load($childId); ?>
                        <div class="sub-product">
                            <a href="<?php echo $block->getBaseUrl() . $childItem->getUrlKey(); ?>">
                                <img src="<?php echo $block->getBaseUrl() . "pub/media/catalog/product" . $childItem->getData('image'); ?>" height="70" alt="docs-org" />
                                <h4><?php echo $block->escapeHtml($childItem->getName()); ?></h4>
                                <!-- <h4>30 Capsule pack</h4> -->
                                <?php if (null !== $childItem->getCustomAttribute('tagline')): ?>
                                    <h5><?= $childItem->getCustomAttribute('tagline')->getValue() ?><h5>
                                <?php endif;  ?>
                                <p><?= /* @escapeNotVerified */ $priceHelper->currency($childItem->getPrice(), true, false) ?></p>
                            </a>
                        </div>
                <?php
                      }
                    }
                ?>
            </div>
        </div>
    <?php endforeach ?>
<?php endif; ?>