<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class=" block-products-list <?php /* @noEscape */ echo $mode; ?>">
        <div class="block-content">
            <?php /* @noEscape */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @noEscape */ echo $mode; ?> <?php /* @noEscape */ echo $mode; ?>">
                <ol class="product-items <?php /* @noEscape */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                    <?php if ($iterator++ != 1): ?></li><?php endif ?>
                    <li class="product-item">
                        <div class="product-item-info">
                            <a href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php echo $block->escapeUrl($block->getProductUrl($_item)) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <div class="product-item-content">
                                  <?php echo $this->helper('Quinoid\CatalogWidget\Helper\Product\Description')->getProductDescription($_item) . "<br>"; ?>
                                </div>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary" data-mage-init='{"redirectUrl":{"url":"<?php echo $block->escapeUrl($block->getAddToCartUrl($_item)) ?>"}}' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary" data-post='<?php /* @noEscape */ echo $postData; ?>' type="button" title="<?php echo $block->escapeHtmlAttr(__('Subscribe')) ?>">
                                                            <span><?php echo $block->escapeHtml(__('Subscribe')) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                    <div class="product-item-price">
                                                      <?php echo $block->getProductPriceHtml($_item, $type) ?>
                                                    </div>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php echo $block->escapeHtml(__('In stock')) ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php echo $block->escapeHtml(__('Out of stock')) ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php
                                        $typeInstance = $_item->getTypeInstance();
                                        $requiredChildrenIds = $typeInstance->getChildrenIds($_item->getId(), true);
                                        foreach ($requiredChildrenIds as $key => $childIdArr) {}
                                        if ($childIdArr != null) {
                                          foreach ($childIdArr as $childId) {
                                            $childItem = $objectManager->get('Magento\Catalog\Model\Product')->load($childId);
                                            ?>
                                            <div class="child-item-info">
                                              <div class="child-item-image">
                                                <?php echo $block->getImage($childItem, $image)->toHtml() ?>
                                              </div>
                                              <div class="child-item-name">
                                                <?php echo $block->escapeHtml($childItem->getName()) ?>
                                              </div>
                                              <div class="child-item-price">
                                                <?php echo $block->getProductPriceHtml($childItem, $type) ?>
                                              </div>
                                            </div><?php
                                          }
                                        }
                                        ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
