<div class="home-container">
<div class="footer-bottom">
  <!-- Footer Payments Block -->
  <div class="footer-payments">
    <?php echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-payments')
                ->toHtml();
    ?>
  </div>
  <!-- Footer Disclaimer Block -->
  <div class="footer-disclaimer">
    <?php
        echo $this->getLayout()
                ->createBlock('Magento\Cms\Block\Block')
                ->setBlockId('footer-disclaimer')
                ->toHtml();
    ?>
  </div>
  <!-- Footer Copyright Block -->
  <div class="footer-copyright">
    <?php
      echo $this->getLayout()
              ->createBlock("Magento\Theme\Block\Html\Footer")
              ->setTemplate("Magento_Theme::html/copyright.phtml")
              ->toHtml();
    ?>
  </div>
</div>
</div>
