
<div class="pdp-bundle-suggestion">
<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
?>
<?php
switch ($type = $block->getType()) {

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;
            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
    <div class="product-item-info">
        <?php foreach ($items as $_item): ?>
            <?php $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId()) ?>
            <?php $images = $product->getMediaGalleryImages() ?>
            <div id="owl-product" class="padding-70 loop owl-carousel product-image-container">
            <?php foreach ($images as $image): ?>
              <div class="item">
                <img src="<?= $image['url'] ?>"/>
              </div>
            <?php endforeach; ?>
            </div>

            <div class="product details product-item-details">
                <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                    <?= $block->escapeHtml($_item->getName()) ?></a>
                </strong>
            </div>
            <div class="product-item short-description">
                <?= /* @escapeNotVerified */ $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_item, $_item->getShortDescription(), 'short_description') ?>
            </div>
            <div class="product-item description">
                <?= /* @escapeNotVerified */ $this->helper('Quinoid\CatalogWidget\Helper\Product\Description')->getProductDescription($_item); ?>
            </div>
            <?php if ($_item->isSaleable()): ?>
                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span> | <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                    </button>
                <?php else: ?>
                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                    ?>
                    <button class="action tocart primary"
                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span> | <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
                    </button>
                <?php endif; ?>
            <?php else: ?>
                <?php if ($_item->getIsSalable()): ?>
                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                <?php else: ?>
                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                <?php endif; ?>
            <?php endif; ?>
            <div class="product-row">
                <div class="row">
                    <?php
                    $typeInstance = $_item->getTypeInstance();
                    $requiredChildrenIds = $typeInstance->getChildrenIds($_item->getId(), true);
                    if ($requiredChildrenIds) {
                        foreach ($requiredChildrenIds as $key => $childIdArr) {}
                        if ($childIdArr != null) {
                            foreach ($childIdArr as $childId) {
                                $childItem = $objectManager->get('Magento\Catalog\Model\Product')->load($childId);
                                ?>
                                <div class="sub-product">
                                    <a href="<?php echo $block->getBaseUrl() . $childItem->getUrlKey(); ?>">
                                        <img src="<?php echo $block->getBaseUrl() . "pub/media/catalog/product" . $childItem->getData('image'); ?>" height="70" alt="docs-org" />
                                        <h4><?php echo $block->escapeHtml($childItem->getName()); ?></h4>
                                        <p><?= /* @escapeNotVerified */ $priceHelper->currency($childItem->getPrice(), true, false) ?></p>
                                    </a>
                                </div>
                            <?php
                            }
                        }
                    }
                    ?>
                </div>
            </div>
            <?php break ?>
        <?php endforeach; ?>
    </div>
<?php endif;?>
</div>
<script type="text/x-magento-init">
    {
    "#owl-product": {
        "OwlCarousel": {
          "center": false,
          "items": 1,
          "dots":true,
          "loop": true,
          "margin": 10,
          "responsive": {
            "0": {
              "items": 1
            },
            "600": {
              "items": 1
            }
          }
        }
      }
    }
</script>
