<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');

?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
   <?php
      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
      $subcategory = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
      $subCats = $subcategory->getChildrenCategories();
      $_helper = $this->helper('Magento\Catalog\Helper\Output');?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
<h1 class="title-heading"><strong>Club </strong>Exclusive</h1>
<div class="home-container">
    <div class="toolbar-wrapper">
      <ul class="sub-cat-ul">
      <?php
      foreach ($subCats as $subcat) {
          $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
          $subcaturl = $subcat->getUrl();
        ?>
          <li class="cat-li">
              <div class="info">
                  <a class="link" href="<?php echo $subcaturl ?>"><?php echo $subcat->getName(); ?></a>
              </div>
          </li>
      <?php } ?>
   </ul>
    <?= $block->getToolbarHtml() ?>
  </div>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                  <div class="product-item-images" style="width:250px">
                     <div class="product-image-container" id="owl-caurosel" data-mage-init='{
                      "OwlCarousel":{
                            "autoPlay": 3000,
                            "items" : 1,
                            "pagination" : true,
                            "itemsDesktop" : [1199,1],
                            "itemsDesktopSmall" : [979,1],
                            "itemsTablet" : [768, 1]
                      }
                    }
                    '>
                      <?php
                          $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                          $item = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                          $productimages = $item->getMediaGalleryImages();
                          foreach($productimages as $child){ ?>
                            <div class="item"><span class="product-image-wrapper">
                              <img class="product-image-photo" src="<?php echo $child->getUrl(); ?>"  alt="<?=$_product->getName();?>" title="<?=$_product->getName();?>"/></span></div>
                      <?php } ?>
                    </div>
                  </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                              <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>

                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
                        <?= $_product->getShortDescription();
                        $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
                        ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart | ')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart | ') ?></span>
                                                <?= /* @escapeNotVerified */ $priceHelper->currency($_product->getFinalPrice(), true, false); ?>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
    <script type="text/x-magento-init">
    {
        ".product-image-container": {
            "OwlCarousel": {
                "autoPlay": false,
                "items": 1,
                "pagination" : true,
                "itemsDesktop": [1199, 1],
                "itemsDesktopSmall": [979, 1],
                "itemsTablet" : [768, 1],
                "autoWidth" : true
            }
        }
    }
  </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
