<?php
/**
 * Created by Magenest.
 * Author: Pham Quang Hau
 * Date: 29/05/2016
 * Time: 02:06
 */
/** @var \Magenest\Stripe\Block\Customer\Subscription\Detail $block */
// @codingStandardsIgnoreFile
$subsDetail = $block->getSubsDetail();
$subscriptionItems = $block->getSubscriptionItem();
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>

<?php if($subsDetail){ ?>
<?php if (($subsDetail['status'] == 'active')||($subsDetail['status'] == 'trialing')) { ?>
    <div style="width: 20%; float: left">
        <a
            href="<?=$block->getCancelUrl($subsDetail['subscription_id'])?>"
            onclick="return confirm('Are you sure you want to cancel this subscription?');"
        >
            <span>Cancel Subscription</span>
        </a>
    </div>
<?php } ?>
<!--    <div style="width: 20%; float: left">-->
<!--        <a-->
<!--                href="-->  <!--"-->
<!--        >-->
<!--            <span>View Invoices</span>-->
<!--        </a>-->
<!--    </div>-->
<br><br>
<div class="block block-order-details-view">
    <div class="block-content">
        <div class="box" style="width: 50%; display: inline; float: left">
            <strong class="box-title">
                <span><?php echo __('Current Status'); ?></span>
            </strong>
            <div class="box-content">
                <table>
                    <tr>
                        <th><?php echo __('Status'); ?></th>
                        <td><?php echo $subsDetail['status']; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Created At'); ?></th>
                        <td><?php echo date("Y-m-d H:i:s", $subsDetail['created']); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Current Period Start'); ?></th>
                        <td><?= $subsDetail['period_start']; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Current Period End'); ?></th>
                        <td><?= $subsDetail['period_end']; ?></td>
                    </tr>
                    <?php if($subsDetail['status'] == 'trialing'){ ?>
                    <tr>
                        <th><?php echo __('Trial Start'); ?></th>
                        <?php if ($subsDetail['trial_start'] != null) { ?>
                            <td><?php echo date("Y-m-d H:i:s", $subsDetail['trial_start']); ?></td>
                        <?php } else { ?>
                            <td><?php echo __('N/A'); ?></td>
                        <?php } ?>
                    </tr>
                    <tr>
                        <th><?php echo __('Trial End'); ?></th>
                        <?php if ($subsDetail['trial_end'] != null) { ?>
                            <td><?php echo date("Y-m-d H:i:s", $subsDetail['trial_end']); ?></td>
                        <?php } else { ?>
                            <td><?php echo __('N/A'); ?></td>
                        <?php } ?>
                    </tr>
                    <?php } ?>
                    <tr>
                        <th><?php echo __('Ended At'); ?></th>
                        <?php if ($subsDetail['ended_at'] != null) { ?>
                            <td><?php echo date("Y-m-d H:i:s", $subsDetail['ended_at']); ?></td>
                        <?php } else { ?>
                            <td><?php echo __('Not yet ended'); ?></td>
                        <?php } ?>
                    </tr>
                    <?php if($subsDetail['canceled_at']){ ?>
                    <tr>
                        <th><?php echo __('Canceled At'); ?></th>
                        <td><?= date("Y-m-d H:i:s",$subsDetail['canceled_at']); ?></td>
                    </tr>
                    <?php } ?>
                </table>
            </div>
        </div>

        <?php foreach ($subscriptionItems as $item){
           $plan = $block->getSubscriptionPlanData($item);
        ?>
        <div class="box" style="width: 50%; display: inline; float: left">
            <strong class="box-title">
                <span><?php echo __('Subscribed Plan'); ?></span>
            </strong>
            <div class="box-content">
                <table>
                    <tr>
                        <th><?php echo __('Plan Name'); ?></th>
                        <td><?php echo $plan['nickname']; ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Quantity'); ?></th>
                        <td><?= $item->getData('quantity') ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Amount'); ?></th>
                        <td><?= $priceHelper->currency(number_format($plan['amount']/100,2),true,false); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Billing Frequency'); ?></th>
                        <td><?php echo __('Every ') . $plan['interval_count'] . ' ' . $plan['interval'] . __('(s)'); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo __('Trial Period (days)'); ?></th>
                        <?php if ($plan['trial_period_days'] != null) { ?>
                            <td><?php echo $plan['trial_period_days']; ?></td>
                        <?php } else { ?>
                            <td><?php echo __('N/A'); ?></td>
                        <?php } ?>
                    </tr>
                </table>
            </div>
        </div>
        <?php } ?>
    </div>
</div>
<?php } ?>