<?php
/**
 * Copyright © Quinoid, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="order-confirm">

  <div class="checkout-success">
      <div class="order-confirm-success-image">
        <div class="order-confirm-img">
          <img src="<?php echo $block->getViewFileUrl('images/order-confirm-pic.png'); ?>" class="image" height="70" alt="docs-org" />
        </div>
        <h1>
          Order Successfully Placed
        </h1>
      </div>
      <div class="order-confirm-heading">
        <h2>Thank you for your purchase! Your order has been received</h2>
      </div>
      <?php if ($block->getOrderId()):?>
          <?php if ($block->getCanViewOrder()) :?>
              <p><?= __('Your order number is:  #<span>%1</span>.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
          <?php  else :?>
              <p><?= __('Your order number is: #<span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
          <?php endif;?>
              <p><?= /* @escapeNotVerified */ __('You will receive an order confirmation email with details of your order and a link to track its progress.') ?></p>
      <?php endif;?>

      <?= $block->getAdditionalInfoHtml() ?>

      <div class="actions-toolbar">
          <div class="primary">
              <a class="action primary continue" href="<?= /* @escapeNotVerified */ $block->getContinueUrl() ?>"><span><?= /* @escapeNotVerified */ __('Continue Shopping') ?></span></a>
          </div>
      </div>
  </div>
  <div class="curve-white"></div>
</div>
